### ISSUE TITLE
wrong execution times and energy consumptions when migrating VM

### ISSUE THREAD

**Issue by bcamus** [simgrid/simgrid#207]
Hello,

As explained below, when migrating a VM which executes a task, it seems that :

- from an energy perspective the whole task is executed on the **destination** host (i.e. only the destination host consumes energy, both during and after the migration).

- the task is computed at the speed of the **source** host only (i.e. even after the migration, the task is executed at the speed of the source host, not the destination one). 

 
Attached is a minimal (Java) example showing this point.
In this example, we consider two hosts connected with a 1000000Bps link : 

- "acme-1" has a speed of 10f
- "acme-2" has a speed of 1000f

Each host has 1 core (but the issue also occurs with multi-core hosts) and consumes 0.0W when idle and 1.0W at full capacity.

On "acme-1", we deploy a VM of 10MB  which executes a task of 1000f.
Then, we immediately start the migration of the VM from "acme-1" to "acme-2 (without dirty-pages).

We check the migration time, the execution time of the task and the energy consumptions of the hosts and we obtain the following output : 

`start migration at time 0.0 | source consumption = 0.0 J | dest consumption = 0.0 J
end of migration at time 11.35056494845361 | source consumption = 0.0 J | dest consumption = 11.35056494845361 J
task of 1000f done at time 100.0 | source consumption = 0.0 J | dest consumption = 100.0 J
`

The issues are  : 
- at the end of the migration (as the VM is still executed on the source host _during_ the migration), the energy consumptions should be the opposite of what is observed (i.e. source consumption = 11.35056494845361 J | dest consumption = 0.0 J). It is interesting to note that this issue disappear if the task ends _during_ the migration (e.g. if the task has a size of 10f instead of 1000f)  : may be the energy consumptions are not updated at the end of the migration ?

- the execution time of the task is wrong as it is only based on the speed of the source host (i.e. 10f). Instead, It should be based on the speed of the source host during the migration, and on the speed of the destination host after the migration -i.e. : 
11.35056494845361 + (1000 - (11.35056494845361*10) )/1000 = 12,2370593 sec.

[SimGrid-BugReport-VM-migration.zip](https://github.com/simgrid/simgrid/files/1176487/SimGrid-BugReport-VM-migration.zip)

**Comment by bcamus** [comment]
Ok, I took a look closer to the problem. Below is a part of the log generated in debug mode (the whole log is attached). When phase 2 of the migration ends we have : 

```
…
[acme-1:__pr_mig_tx:vm(acme-1-acme-2):(4) 11.350565] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-osx-mavericks/build/SimGrid-3.17/src/plugins/vm/VirtualMachineImpl.cpp:166: [surf_vm/DEBUG] suspend VM(vm), where 1 processes exist
[acme-1:__pr_mig_tx:vm(acme-1-acme-2):(4) 11.350565] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-osx-mavericks/build/SimGrid-3.17/src/plugins/vm/VirtualMachineImpl.cpp:173: [surf_vm/DEBUG] suspend worker
…
[acme-1:__pr_mig_tx:vm(acme-1-acme-2):(4) 11.350565] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-osx-mavericks/build/SimGrid-3.17/src/plugins/vm/VirtualMachineImpl.cpp:177: [surf_vm/DEBUG] suspend all processes on the VM done done
…
[11.350565] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-osx-mavericks/build/SimGrid-3.17/src/plugins/vm/VirtualMachineImpl.cpp:277: [surf_vm/DEBUG] migrate VM(vm): set bound (10.000000) at acme-2
[11.350565] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-osx-mavericks/build/SimGrid-3.17/src/plugins/vm/VirtualMachineImpl.cpp:286: [surf_vm/DEBUG] migrate VM(vm): change PM (acme-1 to acme-2)
…
[11.350565] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-osx-mavericks/build/SimGrid-3.17/src/surf/plugins/host_energy.cpp:293: [surf_energy/DEBUG] [get_current_watts] min_power=0.000000, max_power=0.000000, slope=0.000000
[11.350565] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-osx-mavericks/build/SimGrid-3.17/src/surf/plugins/host_energy.cpp:294: [surf_energy/DEBUG] [get_current_watts] Current power (watts) = 1.000000, load = 0.010000
[11.350565] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-osx-mavericks/build/SimGrid-3.17/src/surf/plugins/host_energy.cpp:219: [surf_energy/DEBUG] [update_energy of acme-2] period=[0.00-11.35]; current power peak=1E+03 flop/s; consumption change: 0.00 J -> 11.35 J
…
[11.350565] /Users/bcamus/Dropbox/Post-Doc-Rennes/cosmic/simgrid/src/plugins/vm/VirtualMachineImpl.cpp:80: [surf_vm/DEBUG] assign 10.000000 to vm vm @ pm acme-2
...
```

The execution speed problem is (partially) due to the fact that we keep the previous bound of the VM in the new host (in the code :  [https://github.com/simgrid/simgrid/blob/master/src/plugins/vm/VirtualMachineImpl.cpp#L274](https://github.com/simgrid/simgrid/blob/master/src/plugins/vm/VirtualMachineImpl.cpp#L274).) I don’t understand why do we need to do keep this bound ? Note that this is only a part of the problem : removing this from the code does not change the computing speed of the task, but the VM get at least the expected speed from the PM. May be we need to change the bound of the actions running within the VM too ?

The problem of the energy consumption seems due to the fact that (1) only the PM running the VM is updated, and (2) the energy consumption is updated _after_ the VM has changed of PM. The _two_ PMs (i.e. source and destination) should be updated _before_ the PM change.

I’ll try to found a way to fix these issues.

[migration.txt](https://github.com/simgrid/simgrid/files/1196705/migration.txt)

**Comment by bcamus** [comment]
I think I found the real problem for the energy consumption : suspending/resuming a VM (or more precisely the action related to the VM) does not trigger a signal for updating the energy consumption of the PM. Hence, the two hosts are not updated in migration phase 3 (in the code, [here](https://github.com/simgrid/simgrid/blob/master/src/msg/msg_vm.cpp#L689) for the source, and [here](https://github.com/simgrid/simgrid/blob/master/src/msg/msg_vm.cpp#L312) for the destination).

**Comment by bcamus** [comment]
Ok, I have a patch ready for the energy consumption issue: CpuAction::resume() and CpuAction::suspend() now override Action::resume() and Action::suspend() and trigger a onStateChange signal. I'll Clean my code and prepare a pull request within a few days.

**Comment by mquinson** [comment]
That's a very good news, thanks a lot.

**Comment by mquinson** [comment]
Hello,

 I think that the second part of this bug was #245, which I just closed a few minutes ago. This bug may well be fixed now, but I'm not sure.

I reexecuted your MWE and now get the following output:
```
start migration at time 0.0 | source consumption = 0.0 J | dest consumption = 0.0 J
end of migration at time 11.35056494845361 | source consumption = 11.35056494845361 J | dest consumption = 0.0 J
task of 1000f done at time 100.0 | source consumption = 11.35056494845361 J | dest consumption = 88.64943505154639 J
```

@bcamus is it what was expected? 
Thanks,

**Comment by Shurakai** [comment]
@bcamus Any update on this ?

**Comment by bcamus** [comment]
This bug is not fixed : the execution time of the task is wrong as it is only based on the speed of the source host (i.e. 10f/sec). Instead, It should be based on the speed of the source host during the migration, and on the speed of the destination host after the migration -i.e. :
11.35056494845361 + (1000 - (11.35056494845361*10) )/1000 = 12,2370593 sec.

**Comment by mquinson** [comment]
Here is a way to rerun the MWE (to be executed from the SimGrid directory within the archive):
```
$ (cd src; javac -cp ~/Code/simgrid/build/java/simgrid.jar bug/vmMigration/*java)
$ LD_LIBRARY_PATH=~/Code/simgrid/build/java/lib/ java -cp ~/Code/simgrid/build/java/simgrid.jar:src bug.vmMigration.MainVMmigration
```
The LD_LIBRARY_PATH is probably useless if you enabled the `lib_in_jar` option in cmake, but I find it unpleasant to work with: java examples get recompiled all the time even if they didn't change.
