### ISSUE TITLE
Feature Request: expose clusters as objects

### ISSUE THREAD

**Issue by frs69wq** [simgrid/simgrid#253]
For some simgrid-based projects, such as Wrench and probably Batsim, it could be interesting to have access to the list of clusters in the platform in addition to the low level list of hosts.

A new object could be created at parsing time:
class Cluster {
 std::string id_;
 std::vector<s4u::Host*> host_list;
 kernel::routing::NetPoint* router;
public:
 Cluster(std::string id) : id_(id) {}
 ~Cluster();
 void addHost(s4u::Host* host);
 void addRouter(kernel::routing::NetPoint* router);
 std::string getId();
 std::vector<s4u::Host*> getHostList();
 kernel::routing::NetPoint* getRouter();
}

Then each cluster will be added to a global list somewhere. There is no need for funky methods such as executing something on a whole cluster. It would just be more convenient for users that would like to see that level of the hierarchy.

**Comment by mquinson** [comment]
Hello,

I think you are searching for simgrid::kernel::routing::ClusterZone. You can retrieve a given zone from its name with Engine::getNetzoneByNameOrNull(), or you can traverse the whole tree with Engine::getRoot() and then Zone::getChildren(). 

What is not working right now, is adding hosts and zones using that C++ interface. It's planned for sure but not working yet.

**Comment by frs69wq** [comment]
The objective was not to dynamically add/remove clusters but just to have a convenient way for users to retrieve hosts on  a per cluster basis. So the option based on traversing the Netzone tree is just fine.

I wrote a small teshsuite example that does that as follows:
static void recursiveClusterSearch(simgrid::s4u::NetZone* current, std::vector<simgrid::s4u::NetZone*>* clusters)
{
  for (auto const& elem : *(current->getChildren())) {
    recursiveClusterSearch(elem, clusters);
    if (elem == dynamic_cast<simgrid::kernel::routing::ClusterZone*>(elem))
      clusters->push_back(elem);
  }
}

and then in main:
  std::vector<simgrid::s4u::NetZone*>* clusters = new std::vector<simgrid::s4u::NetZone*>;
  recursiveClusterSearch(e.getNetRoot(), clusters);

after that one can browse this vector of cluster and call the getHosts method of the Netzone class.

Two questions though:
 - simgrid::kernel::routing::ClusterZone is tagged as XBT_PRIVATE so I had to remove that to make the example work
 - shall we do this traversal in an internal SimGrid function, hence add some Engine::getClustersList method or just show to users how to do that in an example?

**Comment by mquinson** [comment]
Yeah, tagging these structures as XBT_PRIVATE is a mistake, probably my own, sorry.

I just pushed some code attempting to provide a templated member allowing to retrieve all zones of a given type. Please tell me what you think of it.

**Comment by mquinson** [comment]
hello, do you miss something else, or could we maybe close that bug?

Thx, Mt.

**Comment by frs69wq** [comment]
Well, one issue remains. The different types of Netzone (ClusterZone, TorusZone, DragonflyZone, ...) that can be used in the templated function are not publicly exposed. This requires to include .hpp from src/kernel/routing which are not available after a make install. This makes the templated function unusable by an external project based on SimGrid. Having the zones declared in something like include/simgrid/kernel/routing.hpp would help.

F.

**Comment by mquinson** [comment]
I think it's done, now. Do you confirm?

**Comment by frs69wq** [comment]
Yes, now that kernel headers are publiq, the initial requested feature is avaibable. Thus closing.
