### ISSUE TITLE
Add ptask L07 resource tracing

### ISSUE THREAD

**Issue by mickours** [simgrid/simgrid#264]
For now ``tracing/uncategorized:yes`` do not provides any resource usage trace in the Pajé output trace of the simulation.

I've tried to had the tracing support for ptask L07 modele support with this patch (folowing the idea of @frs69wq ):
```diff
diff --git a/src/surf/ptask_L07.cpp b/src/surf/ptask_L07.cpp
index b26fa21ee..0c6475c33 100644
--- a/src/surf/ptask_L07.cpp
+++ b/src/surf/ptask_L07.cpp
@@ -5,6 +5,7 @@

 #include "ptask_L07.hpp"
 #include "surf/surf.hpp"
+#include "src/instr/instr_private.hpp" // TRACE_is_enabled(). FIXME: remove by subscribing tracing to the surf signals
 #include "xbt/config.hpp"

 #include <unordered_set>
@@ -80,7 +81,7 @@ double HostL07Model::next_occuring_event(double now)
   return min;
 }

-void HostL07Model::update_actions_state(double /*now*/, double delta)
+void HostL07Model::update_actions_state(double now, double delta)
 {
   for (auto it = std::begin(*get_running_action_set()); it != std::end(*get_running_action_set());) {
     L07Action& action = static_cast<L07Action&>(*it);
@@ -129,6 +130,27 @@ void HostL07Model::update_actions_state(double /*now*/, double delta)
         cnst = action.get_variable()->get_constraint(i);
       }
     }
+    // Add traces
+    if (TRACE_is_enabled()) {
+      int n = action.get_variable()->get_number_of_constraint();
+
+      for (int i = 0; i < n; i++){
+        kernel::lmm::Constraint* constraint = action.get_variable()->get_constraint(i);
+        double value = action.get_variable()->get_value() * action.get_variable()->get_constraint_weight(i);
+        simgrid::kernel::resource::Resource* resource = static_cast<simgrid::kernel::resource::Resource*>(constraint->get_id());
+        LinkL07* link = dynamic_cast<LinkL07*>(resource);
+        CpuL07* cpu = dynamic_cast<CpuL07*>(resource);
+
+        if (link)
+        {
+            TRACE_surf_link_set_utilization(link->get_cname(), action.get_category(), value, now, delta);
+        }
+        else if (cpu)
+        {
+            TRACE_surf_host_set_utilization(cpu->get_cname(), action.get_category(), value,  now, delta);
+        }
+      }
+    }
   }
 }
```

It compiles, but the generated traces are inconsistent and ``pg_dump`` gives me this error:
```
  1 PajeSimulationException: Illegal, trace is not time-ordered in (Line: 10825, Fields: '5, Contents: '9 176.593273 4 2 601174690.222219')
```
It only happen on this events:
```
%EventDef PajeAddVariable 9
%       Time date
%       Type string
%       Container string
%       Value double
%EndEventDef
```
It seems that the variable created in the Paje files have a time value slightly smaller than expected:

```
6 176.593873 1562 5 1541 "Scheduler REQ-REP-10" 
6 176.594473 1563 5 383 "job_ab8457!3-11" 
9 176.593273 4 2 601174690.222219  <---- ERROR IS HERE
9 176.593273 4 5 601174690.222219 
```
It looks like it is interfering with process tracing.

Any idea?

**Comment by frs69wq** [comment]
Hi @mickours,

I changed the way resource usage is traced by leveraging surf signals instead of having duplicated blocks in the different models. 

From commit ff3ef77, using ptaskL07 should make no difference. Could you please try whether it solves your problems?

Cheers

**Comment by mickours** [comment]
Thanks!

I retried on a small setup with your version and face the same issue as my patch:

```
PajeSimulationException: Illegal, trace is not time-ordered in (Line: 326, Fields: '5, Contents: '9 0.000000 3 1 498000000000000.000000')
```
Here is the incriminated lines:
```
12 0.000030 13 28 16
9 0.000000 3 1 498000000000000.000000
6 100.000015 30 12 1 "Scheduler REQ-REP-4"
```
Also, all the events 9 (AddVariable) have a timestamp of 0.0000000, it seems that this event is not added to the trace properly.

**Comment by mickours** [comment]
d883ac7 seems to fix the problem of timestamp. Great!

Still it Iacks ``bandwidth_used`` variable information in the csv that prevents me to reproduce the network topology with usage graph from http://simgrid.gforge.inria.fr/contrib/R_visualization.php

Is it normal that this variable is missing? It is declared in the paje trace with 
``1 7 4 bandwidth_used "0.5 0.5 0.5"`` but the variable is never used afterwards.

**Comment by ClemLbs** [comment]
Hi, 

I am trying to run the [parallel task example program](https://github.com/simgrid/simgrid/blob/master/teshsuite/msg/energy-ptask/energy-ptask.c) from simgrid MSG interface [d883ac7](https://github.com/simgrid/simgrid/commit/d883ac7f9b2786862be1fcb700193f66ceecc030) version, to check tracing capabilities and I face the some problems like mickours.

The [basic example](http://simgrid.gforge.inria.fr/simgrid/latest/doc/tutorial_msg.html) runs perfectly tracing bandwidth_used and power_used but when it comes to parallel task it is causing some troubles.
The parallel task is supposed to run one 7 hosts but the power_used is traced for only one host and bandwidth_used is not traced with the following code : 'XBT_INFO("We can do the same with a timeout of one second enabled.");
    computation_amounts   = xbt_new0(double, host_count);
    communication_amounts = xbt_new0(double, host_count* host_count);

    for (int i = 0; i < host_count; i++){
        computation_amounts[i] = 1e9; // 1 Gflop
    }

    for (int i = 0; i < host_count; i++){
        for (int j = i + 1; j < host_count; j++){
            communication_amounts[i * host_count + j] = 1e7; // 10 MB
        }
    }

    ptask = MSG_parallel_task_create("parallel task", host_count, hosts, computation_amounts, communication_amounts, NULL);
    msg_error_t errcode = MSG_parallel_task_execute_with_timeout(ptask, 1 /* timeout (in seconds)*/);
    xbt_assert(errcode == MSG_TIMEOUT, "Woops, this did not timeout as expected... Please report that bug.");
    MSG_task_destroy(ptask);
    xbt_free(communication_amounts);
    xbt_free(computation_amounts);'

Another strange thing is that when the example comes to do only computation or only communication it fails with the following error (at pj_dump execution) : 

> PajeVariableException: Illegal addition to a variable that has no value (yet) in (Line: 294, Fields: '5, Contents: '9 0.000000 3 7 1.000000')

with the following code : `XBT_INFO("Then, build a parallel task involving only computations and no communication (1 Gflop per node)");
    computation_amounts = xbt_new0(double, host_count);

    for (int i = 0; i < host_count; i++){
        computation_amounts[i] = 1e9; // 1 Gflop
    }

    ptask = MSG_parallel_task_create("parallel exec", host_count, hosts, computation_amounts, NULL /* no comm */, NULL);
    MSG_parallel_task_execute(ptask);
    MSG_task_destroy(ptask);
    xbt_free(computation_amounts);`

(And a last little oddity, simgrid outputs wrong pajé format, per example it defines ContainerType instead of Type in the 0 event).

Do you think it comes from simgrid or I have failed my program (deployment file maybe) ?

Thanks.

**Comment by frs69wq** [comment]
Hi,
Tracing for parallel tasks has been slightly improved (it was impossible before) but is still incomplete. So most of the issues you mention certainly come from SimGrid. 
The ptask model is very specific in SimGrid as it not only combines several resources but also resources of different types into a single object and model. And unfortunately it doesn't mix well with what is done for the other models.
Next week we have a simgrid dev meeting during which I hope we will have a closer look at this tracing of parallel tasks issue.

**Comment by frs69wq** [comment]
Hi,
Commit b1801e7 should improve the tracing of ptasks. According to the quick test I made, all hosts now trace their power_used and bandwidth_used can also be traced.  I also fixed another glitch. The creation date of  a ptask was not correctly saved and always set to 0.
I didn't check the pajé dump though. So I'd like your feedback before closing this issue.

**Comment by ClemLbs** [comment]
Hi,

Thanks for the commit.

It seems to work well for the example but I still have a doubt about the power used because it is tracing the same value for all hosts despite different computation amounts. Maybe I missed something in Simgrid internals and it is doing an average.

Pajé dump is okay except for wrong type names in the pajé file.

**Comment by frs69wq** [comment]
Hi,
This is not perfect yet. @mickours raised an issue with the order of the traces, for which I think I found the (silly) cause. The problem is that we lack of test cases to check whether the produced traces are okay or not.
  
About tracing the same value for all hosts, it's partially normal. Consumption does not depends on the amount of work to do. However, if the amount is not evenly balance among the processes, some will finished earlier and the consumption should change for the other. Is that what you mean? If yes, could you provide a MWE that exemplifies this?

Finally I don't understand your comments about the type names. Please refer to  http://paje.sourceforge.net/download/publication/lang-paje.pdf for the "official" Pajé format. An example is shown on page 17 that looks like our traces.

**Comment by mickours** [comment]
Thanks!

Some issues remains:
- In some cases, I still have the issue explain in https://github.com/simgrid/simgrid/issues/264#issuecomment-389512348
- killed jobs are not providing any traces even if they has run for some time.

**Comment by mquinson** [comment]
Hello,

could you guys provide a MWE that we could integrate as a test about these issues? As @frs69wq said, there is absolutely no test about the tracing of parallel task for now, and the SimGrid philosophy of development is that something that is not tested can be removed since it's probably not working anyway.

There is a plenty of examples of example in SimGrid that you could get inspired of, but in short, the perfect SimGrid test is pleasant and somehow pedagogical to read for the users, it exhaustively tests all features and it's very fast to execute to not bother the developers  running the regression tests. 

Don't bother doing a perfect patch containing the integration and everything. Just give us the files and we'll have the fun with cmake and ctest. 

Thanks in advance,

**Comment by ClemLbs** [comment]
Hi,

This is the very basic example I am using : masterworker_test.c, deployment0.xml and small_platform.xml.
It is almost the same than [this code](https://github.com/simgrid/simgrid/blob/master/teshsuite/msg/energy-ptask/energy-ptask.c).

But if it is normal that each host have the same power_used it seems to work well.
Maybe the MSG interface is too deprecated.

[masterworker_test.txt](https://github.com/simgrid/simgrid/files/2183584/masterworker_test.txt)
[deployment0.txt](https://github.com/simgrid/simgrid/files/2183518/deployment0.txt)
[small_platform.txt](https://github.com/simgrid/simgrid/files/2183519/small_platform.txt)

For the pajé it is probably not a problem, but this is per example the official pajé format for the define container type event :

%EventDef PajeDefineContainerType 0
% Alias string
% Type string
% Name string
%EndEventDef

and this is the output of the simgrid example I am running :

%EventDef PajeDefineContainerType 0
%       Alias string
%       ContainerType string
%       Name string
%EndEventDef

In the type definition "Container" is added despite it is not necessary and pj_dump fails on that.

It the same for the following fields:

SourceContainerType instead of StartContainerType
DestContainerType instead of EndContainerType
SourceContainer instead of StartContainer
DestContainer instead of EndContainer
ContainerType instead of Type

Thanks

**Comment by frs69wq** [comment]
Hi,
Ok, I better understand the issue with the format. In fact, it's not a bug but a feature :) If you look at https://github.com/simgrid/simgrid/blob/master/src/instr/instr_paje_header.cpp you'll say that the header is not the same whether the "basic" flag is set to true or false.
It seems that in your example, basic is set to true. By default, it should be set to false, which means that you probably have a --cfg=tracing/basic:yes on the command line. Is that correct?

**Comment by mickours** [comment]
While trying to debug the kill case, I just stumble upon another bug: #285

**Comment by frs69wq** [comment]
I have augmented examples/s4u/exec-ptasks with a heterogeneous parallel task in which each host has a different amount of flops to execute. This allowed me to test and correct (with the help of @alegrand) the tracing of power_used. The last commit related to this modification is 3bf714c

With regard to the original topic of this issue, I think we are pretty close to a solution. The trace order problem remains an open issue but: 1) it's not related to ptasks and 2) it's unclear the problem comes from SimGrid.

@mickours @ClemLbs, I'm waiting for your feedback before closing this issue.

**Comment by mickours** [comment]
Usage tracing is really working for me now. 

I was also unable to reproduce the timestamp and the kill issue with a simple example. 

The timestamp problem seems to be only triggered in our special mode`batexec`, and I think it comes from some initialisation mess in there.

For the fact that killed ptask are not reporting usage, I think it comes from the way we kill process with the MSG API because it works in the example that is based on S4U. @mpoquet is currently working on fixing this.

So in the end, I think you can close this.

**Comment by ClemLbs** [comment]
It works for me too with the MSG interface.

Thanks
