### ISSUE TITLE
parallel task with zero transfer crashes

### ISSUE THREAD

**Issue by sthibaul** [simgrid/simgrid#87]
Hello,

In StarPU we sometimes have data transfers of zero bytes (data used for synchronization only). It happens that it makes simgrid crash here:

#0  0x00007ffff42278e0 in Action::setData(void*) () from /usr/lib/libsimgrid.so.3.11
#1  0x00007ffff41d5d2b in SIMIX_host_parallel_execute () from /usr/lib/libsimgrid.so.3.11
#2  0x00007ffff41e3d8a in SIMIX_simcall_pre () from /usr/lib/libsimgrid.so.3.11

there, self is NULL. Basically, what we are doing is:

	double *computation = calloc(2, sizeof(*computation));
	double *communication = calloc(4, sizeof(*communication));

	communication[1] = size; // here, size is 0

	MSG_parallel_task_create("copy", 2, hosts, computation, communication, NULL);
...
	MSG_task_execute(task);

I.e. the task has really nothing to do, but simgrid should not crash in that case :)

**Comment by mquinson** [comment]
Hello,

I cannot reproduce the problem: https://github.com/simgrid/simgrid/commit/7b721f422a43ce7faaa999dd6a6c4df68cd6e9dd

**Comment by mquinson** [comment]
I think that the right answer is that you should upgrade to 3.13. This issue was fixed at some point since 3.11.

Thanks for reporting

**Comment by sthibaul** [comment]
I'm still getting the crash with simgrid 3.13, I'll have to dig more reproducing it.

**Comment by sthibaul** [comment]
(gdb) bt
#0  simgrid::surf::Action::setData(void*) (this=0x0, data=0x9ed720) at /tmp/simgrid-3.13/src/surf/surf_interface.cpp:734
#1  0x00007ffff4360bca in SIMIX_execution_parallel_start (name=<optimized out>, host_nb=2, host_list=<optimized out>, flops_amount=0xb819c0, bytes_amount=0xb81e40, amount=<optimized out>, rate=-1)
    at /tmp/simgrid-3.13/src/simix/smx_host.cpp:335
#2  0x00007ffff438a386 in SIMIX_simcall_handle (simcall=0xb82c48, value=0) at /tmp/simgrid-3.13/src/simix/popping_generated.cpp:197

**Comment by adegomme** [comment]
Indeed I see a path where this can happen. this is only triggered if you don't use the ptask_l07 model, that is supposed to be used handle parallel tasks. Martin's test was using ptask_l07, hence the impossibility to reproduce.

**Comment by sthibaul** [comment]
Mmmm, we do use the ptask_L07 model.

**Comment by sthibaul** [comment]
src/core/simgrid.c:	MSG_config("workstation/model", "ptask_L07");

**Comment by mquinson** [comment]
My test cannot reproduce it (unless I'm blind), so I'll try your approach to reproduce it.

```
mquinson@nouzonket:~/Code/simgrid/examples/msg/energy-ptask$ ./energy-ptask ../../platforms/energy_platform.xml --cfg=host/model:ptask_L07
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'host/model' to 'ptask_L07'
[0.000000] [xbt_cfg/INFO] Switching to the L07 model to handle parallel tasks.
[MyHost1:test:(1) 0.000000] [msg_test/INFO] First, build a classical parallel task, with 1 Gflop to execute on each node, and 10MB to exchange between each pair
[MyHost1:test:(1) 300.000000] [msg_test/INFO] Then, build a parallel task involving only computations and no communication (1 Gflop per node)
[MyHost1:test:(1) 310.000000] [msg_test/INFO] Then, build a parallel task with no computation nor communication (synchro only)
[MyHost1:test:(1) 310.000000] [msg_test/INFO] Finally, trick the ptask to do a 'remote execution', on host MyHost2
[MyHost1:test:(1) 320.000000] [msg_test/INFO] Goodbye now!
[320.000000] [msg_test/INFO] Simulation done.
```

**Comment by sthibaul** [comment]
Ooops, sorry, there was an #if simgrid < 3.9 above the MSG_config("workstation/model", "ptask_L07"); line...

**Comment by sthibaul** [comment]
(so we're actually using CLM03)
